version: '3.4'

services:
  koinforge-ui:
    image: koinforge-ui
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:8080
